version: '3.5'

volumes:
  production_traefik: {}

services:
  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    image: crm_production_traefik
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    # Dynamic Configuration
    deploy:
      labels:
        - "traefik.http.routers.api.rule=Host(`traefik.risotech.vn`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
        # Dummy service for Swarm port detection. The port can be any valid integer value.
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
        # Another Rule
    networks:
      - az-network

networks:
    az-network:
        external: true
