
logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]
[log]
  filePath = "/treafik.log"
# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "support@risotech.vn"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
  entryPoint = "http"

[file]
[backends]
  [backends.landing]
    [backends.landing.servers.server1]
      url = "http://landing_django:5000"

[frontends]
  [frontends.landing]
    backend = "landing"
    passHostHeader = true
    [frontends.landing.headers]
      HostsProxyHeaders = ['X-CSRFToken']
    [frontends.landing.routes.dr1]
      rule = "Host:crm.risotech.vn"
